import type { Metadata } from 'next'
import { Italianno, Julius_Sans_One, Merriweather } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import Footer from '@/common/footer'
import Nav from '@/common/nav'
import './globals.css'

const juliusSansOne = Julius_Sans_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--julius-sans-one'
})
const merriweather = Merriweather({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
  variable: '--merriweather'
})
const italianno = Italianno({
  weight: '400',
  subsets: ['latin'],
  variable: '--italianno'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body
        className={`${juliusSansOne.variable} ${merriweather.variable} ${italianno.variable} bg-60-light font-sans text-60-dark`}
      >
        <Nav />
        <div className="pt-16 flex flex-col justify-between min-h-screen">
          {children}
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  )
}

export default RootLayout
